# Generated by Django 6.1.1 on 2026-09-20 12:51

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(editable=False, max_length=8)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('avatar', models.FileField(blank=True, upload_to=accounts.models.avatar_path)),
                ('timezone', models.CharField(choices=[('Asia/Kolkata', 'India (IST)'), ('UTC', 'UTC'), ('Europe/London', 'London'), ('Europe/Berlin', 'Central Europe'), ('America/New_York', 'US Eastern'), ('America/Los_Angeles', 'US Pacific'), ('Asia/Singapore', 'Singapore'), ('Australia/Sydney', 'Sydney')], default='Asia/Kolkata', max_length=40)),
                ('storage_quota_mb', models.PositiveIntegerField(default=500)),
                ('expiry_alert_days', models.PositiveSmallIntegerField(default=30, help_text='Warn this many days before a document expires.')),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
