# Generated by Django 6.1.1 on 2026-09-20 12:51

import django.db.models.deletion
import vault.models
import vault.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('financial', 'Financial & tax'), ('legal', 'Legal'), ('medical', 'Medical'), ('education', 'Education'), ('employment', 'Employment'), ('property', 'Property & housing'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=64, verbose_name='Reference / document number')),
                ('issuer', models.CharField(blank=True, max_length=120, verbose_name='Issued by')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sensitivity', models.CharField(choices=[('standard', 'Standard'), ('sensitive', 'Sensitive - ask for my password before download'), ('critical', 'Critical - password required, no public links')], default='standard', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('trashed', 'In trash')], db_index=True, default='active', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('file', models.FileField(max_length=255, storage=vault.storage.private_storage, upload_to=vault.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('verification_code', models.CharField(default=vault.models.generate_verification_code, editable=False, max_length=20, unique=True)),
                ('public_verification', models.BooleanField(default=False, verbose_name='Public verification page')),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_status', models.CharField(choices=[('unknown', 'Not yet checked'), ('ok', 'Intact'), ('failed', 'Mismatch')], default='unknown', max_length=10)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Account created'), ('login', 'Signed in'), ('logout', 'Signed out'), ('login_failed', 'Failed sign-in'), ('login_blocked', 'Sign-in blocked'), ('reauth', 'Password re-entered'), ('password_change', 'Password changed'), ('profile_update', 'Profile updated'), ('twofa_enable', '2FA enabled'), ('twofa_disable', '2FA disabled'), ('token_create', 'API token created'), ('token_revoke', 'API token revoked'), ('upload', 'Uploaded'), ('version', 'New version'), ('version_restore', 'Version restored'), ('view', 'Viewed'), ('download', 'Downloaded'), ('edit', 'Edited'), ('verify', 'Integrity check'), ('certify', 'Certificate enabled'), ('uncertify', 'Certificate disabled'), ('favorite', 'Favourite toggled'), ('archive', 'Archived'), ('unarchive', 'Unarchived'), ('trash', 'Moved to trash'), ('restore', 'Restored'), ('delete', 'Deleted permanently'), ('share_link_create', 'Share link created'), ('share_link_revoke', 'Share link revoked'), ('share_user', 'Shared with user'), ('unshare_user', 'Access removed'), ('public_view', 'Public link opened'), ('public_download', 'Public download'), ('public_verify', 'Public verification'), ('folder', 'Folder changed'), ('tag', 'Tag changed'), ('bulk', 'Bulk action'), ('export', 'Vault exported')], db_index=True, max_length=24)),
                ('document_title', models.CharField(blank=True, max_length=160)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='vault.document')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[('teal', 'Verdigris'), ('navy', 'Ink'), ('brass', 'Brass'), ('rose', 'Rose'), ('violet', 'Violet'), ('slate', 'Slate')], default='teal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vault.folder'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expiring', 'Expiring soon'), ('expired', 'Expired'), ('share', 'Shared with you'), ('security', 'Security'), ('system', 'System')], default='system', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, max_length=120, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vault.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=vault.models.generate_share_token, editable=False, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('allow_download', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='vault.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='vault.tag'),
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shares', to='vault.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'shared_with'), name='unique_share_per_user')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=255, storage=vault.storage.private_storage, upload_to=vault.models.version_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'number'), name='unique_version_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='unique_folder_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'dedupe_key'), name='unique_notification_key'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_tag_per_owner'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='vault_docum_owner_i_d1d909_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'expiry_date'], name='vault_docum_owner_i_f25b8c_idx'),
        ),
    ]
